parameters:
- name: os
  type: object
  default:
    # windows:
    #   image: windows-latest
    # macOS:
    #   image: macOS-latest
    linux:
      image: ubuntu-latest

stages:
- ${{ each pair in parameters.os }}:
  - template: Install-Hub.yml
    parameters:
      platform: ${{ pair.key }}
      ${{ insert }}: ${{ pair.value }}