parameters:
- name: os
  type: object
  default:
    windows:
      image: vs2017-win2016
    macOS:
      image: macOS-10.15
    linux:
      image: ubuntu-16.04

stages:
- ${{ each pair in parameters.os }}:
  - template: Install-Hub.yml
    condition: always()
    parameters:
      platform: ${{ pair.key }}
      ${{ insert }}: ${{ pair.value }}