stages:
- stage:
  displayName: ${{ format('{0} build agent', parameters.platform) }}
  condition: always()
  jobs:
    - job:
      displayName: ${{ format('{0}', parameters.image) }}
      #timeoutInMinutes: 5
      pool:
        name: 'Azure Pipelines'
        vmImage: ${{ parameters.image }}
      steps:
      - powershell: |
          Install-Module -Name ExternalCommand -Scope CurrentUser -Repository PSGallery -Force
        displayName: 'Install ExternalCommand PS Module'
      - task: PowerShell@2
        condition: always()
        inputs:
          targetType: 'filePath' # Optional. Options: filePath, inline
          filePath: InstallUnityHub.ps1 # Required when targetType == FilePath
          #arguments: # Optional
          #script: '# Write your PowerShell commands here.Write-Host Hello World' # Required when targetType == Inline
          errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
          failOnStderr: true # Optional
          #ignoreLASTEXITCODE: false # Optional
          pwsh: true # Optional
          #workingDirectory: # Optional
      - task: ShellScript@2
        inputs:
          scriptPath: Install-Hub.sh
