on: [pull_request]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unity-hub:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Unity Hub
        run: .\InstallUnityHub.ps1
