on:
  pull_request:
    branches: 
      - '*'
  push:
    branches: main

jobs:
  unity-hub:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Unity Hub
        run: .\InstallUnityHub.ps1
        shell: pwsh
